/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package org.back.rest;

import java.util.Set;
import javax.ws.rs.ApplicationPath;
import javax.ws.rs.core.Application;

/**
 *
 * @author Alejandro Garcia
 */
@ApplicationPath("/rest")
public class JaxRsActivator extends Application{

    @Override
    public Set<Class<?>> getClasses() {
        Set<Class<?>> resources = new java.util.HashSet<Class<?>>();
        addRestResourceClasses(resources);
        return resources;
    }

    /**
     * Do not modify addRestResourceClasses() method.
     * It is automatically re-generated by NetBeans REST support to populate
     * given list with all resources defined in the project.
     */
    private void addRestResourceClasses(Set<Class<?>> resources) {
        resources.add(org.back.rest.NotificacionesRestService.class);
        resources.add(org.back.rest.ProductoRestService.class);
        resources.add(org.back.rest.SubastaRestService.class);
        resources.add(org.back.rest.TestRestService.class);
        resources.add(org.back.rest.interceptor.SubastasAuthenticator.class);
    }
    
}
